import { Link } from 'react-router-dom'
import { Calendar, Upload } from 'lucide-react'

export default function HomePage() {
  return (
    <div className="max-w-4xl mx-auto">
      <div className="text-center mb-12">
        <h1 className="text-4xl font-bold text-gray-900 mb-4">
          Welcome to GymBuddy
        </h1>
        <p className="text-xl text-gray-600">
          Your personal workout tracking companion
        </p>
      </div>

      <div className="grid md:grid-cols-2 gap-6">
        <Link
          to="/import"
          className="bg-white p-8 rounded-lg shadow-md hover:shadow-xl transition-shadow border-2 border-transparent hover:border-blue-500"
        >
          <div className="flex items-center gap-4 mb-4">
            <div className="bg-blue-100 p-3 rounded-lg">
              <Upload className="text-blue-600" size={32} />
            </div>
            <h2 className="text-2xl font-semibold">Import Workouts</h2>
          </div>
          <p className="text-gray-600">
            Upload your workout plans from CSV files generated by Gemini
          </p>
        </Link>

        <Link
          to="/calendar"
          className="bg-white p-8 rounded-lg shadow-md hover:shadow-xl transition-shadow border-2 border-transparent hover:border-blue-500"
        >
          <div className="flex items-center gap-4 mb-4">
            <div className="bg-green-100 p-3 rounded-lg">
              <Calendar className="text-green-600" size={32} />
            </div>
            <h2 className="text-2xl font-semibold">View Calendar</h2>
          </div>
          <p className="text-gray-600">
            See all your workouts organized by date and track your progress
          </p>
        </Link>
      </div>
    </div>
  )
}
